// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer: dynamic(() => import("./Footer")),
  hero_section: dynamic(() => import("./HeroSection")),
  post_content: dynamic(() => import("./PostContent")),
};
